#!/usr/bin/env python3
import os
import random

def main():
    script_path = os.path.join("scripts", "hook.js")
    header_path = os.path.join("jni", "hook_bytes.h")

    if not os.path.exists(script_path):
        print(f"Error: {script_path} not found.")
        return

    with open(script_path, "r", encoding="utf-8") as f:
        js_code = f.read()

    # Convert JS code to bytes
    js_bytes = js_code.encode("utf-8")

    # Stealth: rotating 4-byte XOR key (bukan 1 byte) agar dekripsi trivial
    # via analisis frekuensi tidak langsung berhasil. Dekripsi di C++:
    #   plain[i] = hook_bytes[i] ^ hook_xor_key[i & 3]
    # Format cache OTA (ENC\x01 + 1-byte 0x5B) SENGAJA tidak diubah demi
    # kompatibilitas cache lama di device.
    xor_key = bytes(random.randint(1, 255) for _ in range(4))

    # Encrypt the bytes
    encrypted_bytes = bytearray(
        b ^ xor_key[i % 4] for i, b in enumerate(js_bytes)
    )

    # Ensure target directory exists
    os.makedirs(os.path.dirname(header_path), exist_ok=True)

    # Write the C header file
    with open(header_path, "w", encoding="utf-8") as f:
        f.write("/* Automatically generated by encrypt.py. Do not edit. */\n")
        f.write("#ifndef HOOK_BYTES_H\n")
        f.write("#define HOOK_BYTES_H\n\n")
        f.write(
            "const unsigned char hook_xor_key[4] = {"
            + ", ".join(hex(b) for b in xor_key)
            + "};\n"
        )
        f.write(f"const unsigned int hook_bytes_len = {len(encrypted_bytes)};\n\n")
        f.write("const unsigned char hook_bytes[] = {\n    ")

        # Format bytes nicely (12 per line)
        for i, b in enumerate(encrypted_bytes):
            f.write(f"{hex(b)}, ")
            if (i + 1) % 12 == 0:
                f.write("\n    ")

        f.write("\n};\n\n")
        f.write("#endif /* HOOK_BYTES_H */\n")

    print(f"Successfully encrypted {script_path} into {header_path}")
    print("XOR Key: [" + ", ".join(hex(b) for b in xor_key) + "]")

if __name__ == "__main__":
    main()
