#!/usr/bin/env python3
import os
import random

def main():
    script_path = os.path.join("scripts", "hook.js")
    header_path = os.path.join("jni", "hook_bytes.h")

    if not os.path.exists(script_path):
        print(f"Error: {script_path} not found.")
        return

    with open(script_path, "r", encoding="utf-8") as f:
        js_code = f.read()

    # Convert JS code to bytes
    js_bytes = js_code.encode("utf-8")
    
    # Generate a random 1-byte XOR key (non-zero)
    xor_key = random.randint(1, 255)
    
    # Encrypt the bytes
    encrypted_bytes = bytearray(b ^ xor_key for b in js_bytes)

    # Ensure target directory exists
    os.makedirs(os.path.dirname(header_path), exist_ok=True)

    # Write the C header file
    with open(header_path, "w", encoding="utf-8") as f:
        f.write("/* Automatically generated by encrypt.py. Do not edit. */\n")
        f.write("#ifndef HOOK_BYTES_H\n")
        f.write("#define HOOK_BYTES_H\n\n")
        f.write(f"const unsigned char xor_key = {hex(xor_key)};\n")
        f.write(f"const unsigned int hook_bytes_len = {len(encrypted_bytes)};\n\n")
        f.write("const unsigned char hook_bytes[] = {\n    ")
        
        # Format bytes nicely (12 per line)
        for i, b in enumerate(encrypted_bytes):
            f.write(f"{hex(b)}, ")
            if (i + 1) % 12 == 0:
                f.write("\n    ")
                
        f.write("\n};\n\n")
        f.write("#endif /* HOOK_BYTES_H */\n")

    print(f"Successfully encrypted {script_path} into {header_path}")
    print(f"XOR Key: {hex(xor_key)}")

if __name__ == "__main__":
    main()
